<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>

  <PropertyGroup>
    <FanControlPath Condition="'$(FanControlPath)' == ''">C:\Program Files (Winget)\Rem0o.FanControl</FanControlPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="FanControl.Plugins">
      <HintPath>$(FanControlPath)\FanControl.Plugins.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
